# Generated by Django 5.0.3 on 2024-03-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color1', models.CharField(max_length=40)),
                ('color2', models.CharField(max_length=40)),
                ('color3', models.CharField(max_length=40)),
                ('color4', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Shapes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fa_class', models.CharField(max_length=200)),
            ],
        ),
    ]
